 var DrawLayer = new Array();
 var DrawCanvas = new Array();
 var currentLayer = 1;
 var currentCanvas = 1;
 var zCurrentCanvasMode = 'rect';
 var editHistoryNumber = 0;
 var editHistory = new Array();
 var mouseIsDown = new Boolean();
 var clipboardTagStr = "";
 var clipboardAtt;
 var initHistory;
 var cloneFrameEnabled = new Boolean(true);
 var Colorobj;
 var picker;