/*Auto-Generated Ajax Animator Version config (Markup Version II)*/
/*Generated By versions.php in /server/dev/compile/*/
Ax.set_version( /*START*/
{"app":"Ajax Animator","build":358,"release":"0.2","dev":true,"stability":"Alpha","date":1216411646.98}
/*STOP*/ )
/*End Of File*/
