/*Auto-Generated Ajax Animator Version config (Markup Version II)*/
/*Generated By versions.php in /server/dev/compile/*/
Ax.set_version( /*START*/
{"app":"Ajax Animator","build":439,"release":"0.2","dev":false,"stability":"Beta RC1","date":1217781494.54}
/*STOP*/ )
/*End Of File*/
