/*Auto-Generated Ajax Animator Version config (Markup Version II)*/
/*Generated By versions.php in /server/dev/compile/*/
Ax.set_version( /*START*/
{"app":"Ajax Animator","build":504,"release":"0.20.01","dev":false,"stability":"Beta RC2","date":1218114627.07}
/*STOP*/ )
/*End Of File*/
