/*Auto-Generated Ajax Animator Version config (Markup Version II)*/
/*Generated By versions.php in /server/dev/compile/*/
Ax.set_version( /*START*/
{"app":"Ajax Animator","build":772,"release":"0.20.05 Wave","dev":false,"stability":"Beta","date":1325374722.7367}
/*STOP*/ )
/*End Of File*/
