/*Auto-Generated Ajax Animator Version config (Markup Version II)*/
/*Generated By versions.php in /server/dev/compile/*/
Ax.set_version( /*START*/
{"app":"Ajax Animator","build":768,"release":"0.20.05 Wave","dev":false,"stability":"Beta","date":1266453952.81}
/*STOP*/ )
/*End Of File*/
