{
layout:"border",
border:false,
window:{
  layout:"fit"
},
items:[{
    region:"center",
    title:"Canvas",
    layout:"fit",
    border:true,
    items:[{
        xtype:"tabpanel",
        activeTab:1,
        tabPosition:"bottom",
        border:false,
        items:[{
            xtype:"panel",
            title:"Canvas",
            layout:"fit",
            html:"Draw here!\n<br>\n-Replace RichDraw with either OnlyPaths or Prototype Graphic Frameworks editor\n<br>\n[Support IE]\n<br>\nAlso: Opacity\n",
            border:false
          },{
            xtype:"panel",
            title:"Preview",
            layout:"fit"
          },{
            xtype:"panel",
            title:"Animations",
            layout:"fit",
            html:"Share Animations by you and others!"
          }]
      }]
  },{
    region:"north",
    title:"Timeline",
    split:true,
    collapsible:true,
    titleCollapse:true,
    height:100,
    border:true
  },{
    region:"south",
    title:"Properties",
    split:true,
    collapsible:true,
    titleCollapse:true,
    height:60
  },{
    region:"west",
    title:"Tools",
    split:true,
    collapsible:false,
    titleCollapse:true,
    width:50,
    border:true
  },{
    region:"east",
    title:"Misc",
    split:true,
    collapsible:true,
    titleCollapse:true,
    width:130,
    layout:"fit",
    border:true,
    items:[{
        xtype:"tabpanel",
        activeTab:1,
        border:false,
        items:[{
            xtype:"panel",
            title:"Library",
            layout:"fit",
            items:[{
                layout:"accordion",
                layoutConfig:{
                  activeOnTop:false,
                  animate:true,
                  autoWidth:true,
                  collapseFirst:false,
                  fill:true,
                  hideCollapseTool:false,
                  titleCollapse:true
                },
                border:false,
                items:[{
                    title:"History",
                    autoHeight:true,
                    border:false
                  },{
                    title:"Clipboard",
                    autoHeight:true,
                    border:false
                  },{
                    title:"Library",
                    autoHeight:true,
                    border:false
                  },{
                    title:"Misc",
                    autoHeight:true,
                    html:"None Yet :P",
                    border:false
                  }]
              }]
          },{
            xtype:"panel",
            title:"User",
            border:false,
            items:[{
                xtype:"form",
                title:"Login Form",
                border:false,
                items:[{
                    xtype:"textfield",
                    fieldLabel:"Username",
                    name:"textvalue"
                  },{
                    xtype:"textfield",
                    fieldLabel:"Password",
                    name:"textvalue",
                    inputType:"password"
                  }]
              },{
                xtype:"form",
                title:"Registration Form",
                border:false,
                hidden:true,
                items:[{
                    xtype:"textfield",
                    fieldLabel:"Username",
                    name:"textvalue"
                  },{
                    xtype:"textfield",
                    fieldLabel:"Password",
                    name:"textvalue",
                    inputType:"password"
                  },{
                    xtype:"textfield",
                    fieldLabel:"Password",
                    name:"textvalue",
                    inputType:"password"
                  },{
                    xtype:"button",
                    text:"Register Account"
                  }]
              },{
                xtype:"panel",
                title:"Profile",
                html:"EEEW!!! Your face is too ugly for anyone to consider profiling that!",
                border:false,
                hidden:true
              },{
                xtype:"button",
                text:"Login"
              }]
          }]
      }]
  }]
}