/*Auto-Generated Ajax Animator Version config (Markup Version II)*/
/*Generated By versions.php in /server/dev/compile/*/
Ax.set_version( /*START*/
{"app":"Ajax Animator","build":201,"release":"0.2","dev":true,"stability":"Pre Alpha","date":1214606301.78}
/*STOP*/ )
/*End Of File*/
