/*Auto-Generated Ajax Animator Version config (Markup Version II)*/
/*Generated By versions.php in /server/dev/compile/*/
Ax.set_version( /*START*/
{"app":"Ajax Animator","build":437,"release":"0.2","dev":true,"stability":"Alpha","date":1217768844.06}
/*STOP*/ )
/*End Of File*/
